---
- name: Create file
  hosts: iaas
  roles:
    - create_file

- name: Get host information
  hosts: all
  roles:
    - get_host_info
  tasks:
    - debug: msg="The server {{hostname.stdout}} has installed linux distribution {{system_info.stdout}}"
